version: '3'

services:

  container2:

    # Imageを作るための設定
    build:

      # buildするときのカレントディレクトリ
      context: ./

    # buildしたimageにつける名前
    image: custom

    # # TRY: 実行時の環境変数の上書き
    # environment:
    #   MESSAGE_PREFIX: "overwrite"

    # # TRY: mongodbを追加してみる
    # links:
    #   - mongo:mongo

  # # TRY: mongodbを追加してみる
  # mongo:
  #   image: mongo:3.4
